### ISSUE TITLE
When a file is "already present" do an e-tag check to make sure its the same file

### ISSUE THREAD

**Issue by sylvinite** [genomic-medicine-sweden/NGPIris#35]
**What needs to be done:**

**Suggestions on how to get it done:**

**What are the arguments for getting it done:**

**Task is considered finished when:**

**Comment by sylvinite** [comment]
Subtask of #33

**Comment by NisseBoman** [comment]
please see https://support.hitachivantara.com/download/epcra/arc0373.pdf on page 137 for more information on how to interact with HCP using the Etag

**Comment by JPWerling** [comment]
Keep in mind that the generated etags are chunk size-dependent when using multipart upload. A check for similarity can therefore only work under the assumption that the chunk size has never changed.

**Comment by erik-brink** [comment]
After a bit of research, it looks like this isn't possible for various reasons
